// <auto-generated />
using System;
using FlowerShop.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowerShop.DAL.Migrations
{
    [DbContext(typeof(FlowerShopDbContext))]
    [Migration("20260427073521_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowerShop.DAL.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Background")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CtaText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Banners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Background = "linear-gradient(135deg,#c84b6b,#8b2d47)",
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 901, DateTimeKind.Local).AddTicks(4289),
                            CtaText = "Mua Ngay",
                            IsActive = true,
                            SortOrder = 1,
                            Subtitle = "Ưu đãi đặc biệt - Giảm 20% tất cả hoa hồng",
                            Title = "Valentine 2024"
                        },
                        new
                        {
                            Id = 2,
                            Background = "linear-gradient(135deg,#c9973a,#8b6520)",
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 901, DateTimeKind.Local).AddTicks(4312),
                            CtaText = "Khám Phá",
                            IsActive = true,
                            SortOrder = 2,
                            Subtitle = "Miễn phí giao hàng cho đơn từ 500k",
                            Title = "Khai Xuân Giáp Thìn"
                        },
                        new
                        {
                            Id = 3,
                            Background = "linear-gradient(135deg,#4a7c59,#2d5a3a)",
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 901, DateTimeKind.Local).AddTicks(4315),
                            CtaText = "Xem Ngay",
                            IsActive = true,
                            SortOrder = 3,
                            Subtitle = "Hàng nhập khẩu chính hãng, giá tốt nhất",
                            Title = "Lan Hồ Điệp Mới Về"
                        });
                });

            modelBuilder.Entity("FlowerShop.DAL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Emoji")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Hoa Sinh Nhật",
                            Color = "#f7d6df",
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6010),
                            Emoji = "🎂",
                            IsActive = true,
                            Slug = "birthday",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Hoa Khai Trương",
                            Color = "#fff0d6",
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6033),
                            Emoji = "🏮",
                            IsActive = true,
                            Slug = "opening",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Lan Hồ Điệp",
                            Color = "#ede6ff",
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6036),
                            Emoji = "🌸",
                            IsActive = true,
                            Slug = "orchid",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Hoa Cưới",
                            Color = "#d6f0f7",
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6038),
                            Emoji = "💍",
                            IsActive = true,
                            Slug = "wedding",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Hoa Tang Lễ",
                            Color = "#e8e8e8",
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6039),
                            Emoji = "🕊️",
                            IsActive = true,
                            Slug = "condolence",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Hoa Tình Yêu",
                            Color = "#ffd6d6",
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6041),
                            Emoji = "❤️",
                            IsActive = true,
                            Slug = "love",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("FlowerShop.DAL.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("FlowerShop.DAL.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiverAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverPhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FlowerShop.DAL.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("FlowerShop.DAL.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Badge")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Img")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoldQuantity")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "hot",
                            CategoryId = 6,
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6348),
                            Description = "Bó hoa hồng đỏ tươi cao cấp, 20 bông hoa hồng Đà Lạt kết hợp lá xanh sang trọng. Phù hợp làm quà tặng người yêu nhân ngày Valentine, kỷ niệm.",
                            Img = "🌹",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            Price = 450000m,
                            ProductName = "Bó Hoa Hồng Đỏ Tình Yêu",
                            Rating = 4.8m,
                            ReviewCount = 124,
                            SalePrice = 380000m,
                            SoldQuantity = 312,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Badge = "sale",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6363),
                            Description = "Giỏ hoa sinh nhật tone pastel nhẹ nhàng với hoa cúc, hoa hồng phấn, lisianthus. Màu sắc tươi vui, thích hợp cho mọi lứa tuổi.",
                            Img = "🌷",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            Price = 650000m,
                            ProductName = "Giỏ Hoa Sinh Nhật Pastel",
                            Rating = 4.9m,
                            ReviewCount = 89,
                            SalePrice = 550000m,
                            SoldQuantity = 201,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6368),
                            Description = "Chậu lan hồ điệp trắng cao cấp, 2 cành 12-15 bông. Chăm sóc kỹ lưỡng, hoa tươi lâu 30-45 ngày. Sang trọng, thanh lịch.",
                            Img = "🌸",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = true,
                            Price = 1200000m,
                            ProductName = "Lan Hồ Điệp Trắng Tinh Khôi",
                            Rating = 5.0m,
                            ReviewCount = 56,
                            SoldQuantity = 98,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 4,
                            Badge = "sale",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6372),
                            Description = "Kệ hoa khai trương 2 tầng rực rỡ, mang ý nghĩa may mắn, thịnh vượng. Kết hợp hoa cúc, hồng, cát tường màu đỏ-vàng.",
                            Img = "🏵️",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            Price = 2500000m,
                            ProductName = "Hoa Khai Trương May Mắn",
                            Rating = 4.7m,
                            ReviewCount = 43,
                            SalePrice = 2200000m,
                            SoldQuantity = 87,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 5,
                            Badge = "hot",
                            CategoryId = 4,
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6376),
                            Description = "Bó cầm tay cô dâu sang trọng với hoa hồng trắng, baby breath, phong lan trắng. Kết hợp ribbon lụa cao cấp.",
                            Img = "💐",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            Price = 800000m,
                            ProductName = "Bó Hoa Cưới Cô Dâu",
                            Rating = 4.9m,
                            ReviewCount = 112,
                            SoldQuantity = 234,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 6,
                            Badge = "sale",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6379),
                            Description = "Bó hoa hướng dương tươi sáng, mang năng lượng tích cực. Kết hợp lá xanh tươi, gói giấy kraft thân thiện.",
                            Img = "🌻",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = true,
                            Price = 350000m,
                            ProductName = "Hoa Hướng Dương Rực Rỡ",
                            Rating = 4.6m,
                            ReviewCount = 78,
                            SalePrice = 300000m,
                            SoldQuantity = 156,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6382),
                            Description = "Giỏ hoa tang lễ trang nhã, màu trắng và tím nhạt. Thể hiện sự tôn trọng và chia sẻ nỗi đau với gia đình.",
                            Img = "🕊️",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            Price = 500000m,
                            ProductName = "Giỏ Hoa Chia Buồn",
                            Rating = 4.5m,
                            ReviewCount = 34,
                            SoldQuantity = 67,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 8,
                            Badge = "new",
                            CategoryId = 6,
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6385),
                            Description = "Bó tulip nhập khẩu Hà Lan đủ màu sắc: đỏ, vàng, tím, hồng. Hoa tươi nhập về 3 lần/tuần.",
                            Img = "🌷",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = true,
                            Price = 520000m,
                            ProductName = "Bó Hoa Tulip Hà Lan",
                            Rating = 4.8m,
                            ReviewCount = 67,
                            SalePrice = 460000m,
                            SoldQuantity = 143,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6389),
                            Description = "Chậu lan hồ điệp tím cao cấp, 2 cành 10-12 bông. Màu tím quý phái, phù hợp làm quà biếu.",
                            Img = "🌺",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = true,
                            Price = 1500000m,
                            ProductName = "Lan Hồ Điệp Tím Hoàng Gia",
                            Rating = 4.9m,
                            ReviewCount = 29,
                            SoldQuantity = 54,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 10,
                            Badge = "sale",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6392),
                            Description = "Kệ hoa khai trương cao cấp 3 tầng, thiết kế hoành tráng. Toàn hoa tươi nhập khẩu, đảm bảo tươi 5-7 ngày.",
                            Img = "🌼",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            Price = 3500000m,
                            ProductName = "Kệ Hoa Khai Trương Vạn Phát",
                            Rating = 4.8m,
                            ReviewCount = 21,
                            SalePrice = 3000000m,
                            SoldQuantity = 45,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6395),
                            Description = "Bó hoa hồng vàng 15 bông, tượng trưng cho tình yêu vĩnh cửu và sự trân trọng. Kết hợp gypsophila trắng.",
                            Img = "🌼",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            Price = 680000m,
                            ProductName = "Hoa Hồng Vàng Sang Trọng",
                            Rating = 4.7m,
                            ReviewCount = 45,
                            SoldQuantity = 98,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 12,
                            Badge = "hot",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6398),
                            Description = "Giỏ hoa sinh nhật cao cấp kết hợp hoa và chocolate Ferrero Rocher, gấu bông dễ thương. Món quà hoàn hảo.",
                            Img = "🎁",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            Price = 1200000m,
                            ProductName = "Giỏ Hoa Sinh Nhật VIP",
                            Rating = 5.0m,
                            ReviewCount = 38,
                            SalePrice = 980000m,
                            SoldQuantity = 72,
                            StockQuantity = 15
                        });
                });

            modelBuilder.Entity("FlowerShop.DAL.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Stars = 5,
                            Text = "Hoa rất đẹp, tươi lâu, đóng gói cẩn thận. Giao nhanh trong 2h. Sẽ ủng hộ dài dài!",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Stars = 4,
                            Text = "Hoa đẹp, màu sắc chuẩn như ảnh. Hơi trễ so với giờ hẹn 30 phút nhưng thông cảm được.",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3,
                            Stars = 5,
                            Text = "Lan đẹp tuyệt vời! Mua tặng sếp nhân ngày khai trương, được khen ngợi nhiều. Rất hài lòng!",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("FlowerShop.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 874, DateTimeKind.Local).AddTicks(6453),
                            Email = "admin@monglan.vn",
                            FullName = "Quản Trị Viên",
                            IsActive = true,
                            PasswordHash = "9dlUIpr23JllA57gEZDzjA==.ZDSPh7tTKI3JWMPRxXklhXac8/oS+PPmYxvKlRDDxRY=",
                            Phone = "0901234567",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "123 Nguyễn Huệ, Quận 1, TP.HCM",
                            CreatedDate = new DateTime(2026, 4, 27, 14, 35, 18, 888, DateTimeKind.Local).AddTicks(2994),
                            Email = "test@monglan.vn",
                            FullName = "Nguyễn Văn Kiểm Thử",
                            IsActive = true,
                            PasswordHash = "62JkwKPjjiNSuEX+PK1pkw==.nk3d07hgqb4iwNsWNGwrKPqVtItNWzueXf0fNFp10HE=",
                            Phone = "0909876543",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("FlowerShop.DAL.Models.Order", b =>
                {
                    b.HasOne("FlowerShop.DAL.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowerShop.DAL.Models.OrderDetail", b =>
                {
                    b.HasOne("FlowerShop.DAL.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerShop.DAL.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FlowerShop.DAL.Models.Product", b =>
                {
                    b.HasOne("FlowerShop.DAL.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FlowerShop.DAL.Models.Review", b =>
                {
                    b.HasOne("FlowerShop.DAL.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerShop.DAL.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowerShop.DAL.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FlowerShop.DAL.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("FlowerShop.DAL.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("FlowerShop.DAL.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
